apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
kind: Kustomization
namespace: kubeflow
patchesJson6902:
- path: seldon-mutating-webhook-configuration-kubeflow-MutatingWebhookConfiguration.yaml
  target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: seldon-mutating-webhook-configuration-kubeflow
    version: v1beta1
- path: seldon-validating-webhook-configuration-kubeflow-ValidatingWebhookConfiguration.yaml
  target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: seldon-validating-webhook-configuration-kubeflow
    version: v1beta1
