apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
configurations:
- overlays/istio/params.yaml
images:
- name: gcr.io/kubeflow-images-public/profile-controller
  newName: quay.io/kubeflow/profile-controller
  newTag: v0.7.0
kind: Kustomization
namespace: kubeflow
resources:
- overlays/istio/virtual-service.yaml
