apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
- overlays/istio
images:
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newName: quay.io/kubeflow/jupyter-web-app
  newTag: v1.0.0
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- overlays/openshift/config-map.yaml
