apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-controller
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  name: argo-metrics
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: telemetry
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: workflow-controller
  sessionAffinity: None
  type: ClusterIP
