apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  kustomize.component: cert-manager
kind: Kustomization
namespace: cert-manager
resources:
- overlays/self-signed/cluster-issuer.yaml
