apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../base
patchesStrategicMerge:
- config-map.yaml

images:
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newTag: v1.0.0
  newName: quay.io/kubeflow/jupyter-web-app
