apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: gcr.io/kubeflow-images-public/notebook-controller
  newTag: v1.0.0
  newName: quay.io/kubeflow/notebook-controller

patchesStrategicMerge:
- addfsgroup-env.yaml
