apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#patchesStrategicMerge:
#- katib-controller-deployment.yaml
patchesStrategicMerge:
- katib-mysql-secret.yaml
- katib-mysql-deployment-patch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: katib-controller
  path: katib-controller-deployment.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: katib-mysql
  path: katib-mysql-deployment.yaml

images:
- name: mysql
  newTag: "latest"
  newName: registry.redhat.io/rhscl/mysql-80-rhel7
