bases:
- ../../base

patchesJson6902:
- target:
    kind: MutatingWebhookConfiguration
    version: v1beta1
    group: admissionregistration.k8s.io
    name: seldon-mutating-webhook-configuration-kubeflow
  path: patchport.yaml

- target:
    kind: ValidatingWebhookConfiguration
    version: v1beta1
    group: admissionregistration.k8s.io
    name: seldon-validating-webhook-configuration-kubeflow
  path: vpatchport.yaml
