apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- overlays/openshift/deployment.yaml
resources:
- overlays/openshift/serviceaccount.yaml
